services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/html:/usr/share/nginx/html
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridg
